// <auto-generated />
namespace Locadora.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class TBItemFilmeAddValor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TBItemFilmeAddValor));
        
        string IMigrationMetadata.Id
        {
            get { return "201909272312396_TBItemFilmeAddValor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
